### ISSUE TITLE
New GPTs Submit: There's An API For That

### ISSUE THREAD

**Issue by alric05** [ai-boost/Awesome-GPTs#178]
1. 🤖 There's An API For That 
   - The #1 API Finder, available for over 1000 tasks.
   - [Chat now](https://chat.openai.com/g/g-LrNKhqZfA-there-s-an-api-for-that-the-1-api-finder)
   - Submit by [@AIFever]

**Comment by simonprovost** [comment]
You could provide a PR yourself if you want that to be faster merged !

**Comment by alric05** [comment]
It's not mine but I found it quite useful so thought it should be added to the list.

**Comment by simonprovost** [comment]
Why not doing the PR anyway? :) As long as "submit by" is the correct individual.

**Comment by alric05** [comment]
Because idk how to...

**Comment by simonprovost** [comment]
This below coud  definitely help if ever you would like to experience yourself with such a thing. Otherwise @ai-boost will do it for ya as soonish as feasible!

https://docs.github.com/en/desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request-from-github-desktop

**Comment by ai-boost** [comment]
Let me add this, thx for your all! 🌻 @simonprovost @alric05
